#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jun  3 21:38:09 2017

@author: shahrooz
"""

# There are five major data types: numbers, strings, lists,  tuples, dictionary or maps
    